import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { formatDate, skillNames, stageText } from "../teacherLabels";

export function Metric({ label, value, helper }: any) { return <div className="teacher-metric"><span>{label}</span><strong>{value ?? "-"}</strong><small>{helper}</small></div>; }
export function MarkdownPanel({ children }: any) { return <div className="teacher-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{children}</ReactMarkdown></div>; }
export function SkillDistribution({ items = [] }: any) { const total = items.reduce((sum: number, x: any) => sum + Number(x.count || 0), 0); return <div className="teacher-bars">{items.map((x: any) => <div key={x.skill_id || x.label}><div><strong>{x.skill_name || skillNames[x.skill_id] || x.skill_id || x.label}</strong><span>{x.count}</span></div><i><b style={{ width: `${total ? Math.max(x.count / total * 100, 4) : 0}%` }} /></i></div>)}{!items.length && <p className="muted">暂无数据</p>}</div>; }
export function QuestionTopics({ items = [] }: any) { return <div className="teacher-topic-list">{items.map((x: any) => <article key={x.id || x.label}><strong>{x.label}</strong><span>{x.count} 次</span><div>{(x.keywords || []).slice(0, 5).map((k: string) => <em key={k}>{k}</em>)}</div>{x.examples?.[0] && <p>{x.examples[0]}</p>}</article>)}{!items.length && <p className="muted">暂无数据</p>}</div>; }
export function StudentDetailView({ detail }: any) { const p = detail.process || {}; return <div className="drawer-sections"><section><h3>会话状态</h3><div className="detail-grid">{[["阶段",stageText(p.stage)],["Skill",skillNames[p.current_skill]||p.current_skill||"未识别"],["追问",`${p.socratic_rounds||0} 轮`],["下一步",p.next_task||"-"]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></section><section><h3>Writing context</h3><pre>{JSON.stringify(detail.writing_context, null, 2)}</pre></section><section><h3>Route history</h3>{detail.route_history?.map((x:any,i:number)=><p key={i}>{stageText(x.stage)} · {String(x.intent||"")} · {String(x.reason||"")}</p>)}</section><section><h3>Messages</h3>{detail.messages?.map((x:any,i:number)=><article className="drawer-message" key={i}><strong>{x.role}</strong><p>{x.content}</p></article>)}</section><section><h3>Skill events</h3>{detail.skill_events?.map((x:any,i:number)=><p key={i}>{skillNames[x.skill_id]||x.skill_id} · {x.event_type} · {formatDate(x.created_at)}</p>)}</section></div>; }
export function StudentDrawer({ open, tab, onTab, onClose, summary, detail, loading }: any) { if (!open) return null; return <div className="teacher-drawer-backdrop" onMouseDown={onClose}><aside className="teacher-drawer" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><h2>学生过程</h2><button onClick={onClose} aria-label="关闭">×</button></header><nav><button className={tab==="summary"?"active":""} onClick={()=>onTab("summary")}>过程摘要</button><button className={tab==="detail"?"active":""} onClick={()=>onTab("detail")}>详细记录</button></nav>{loading ? <p>加载中...</p> : tab==="summary" ? <><MarkdownPanel>{summary?.markdown||"暂无摘要"}</MarkdownPanel>{summary && <div className="drawer-lists"><h3>教师建议</h3><p>{summary.teacher_questions?.join("、")||"-"}</p><h3>学生下一步</h3><p>{summary.student_next_tasks?.join("、")||"-"}</p><h3>教师确认项</h3><p>{summary.teacher_confirmations?.join("、")||"-"}</p></div>}</> : detail ? <StudentDetailView detail={detail}/> : <p>暂无详细记录</p>}</aside></div>; }
export function ImportAnalysisView({ analysis }: any) { if (!analysis) return null; const distributions=[["Skill 分布",analysis.skill_counts],["阶段分布",analysis.stage_counts],["Intent 分布",analysis.intent_counts],["Risk 分布",analysis.risk_counts]]; return <div className="import-full"><div className="metric-row"><Metric label="总记录" value={analysis.total_records} helper={analysis.filename}/><Metric label="已解析" value={analysis.parsed_records} helper="parsed records"/><Metric label="已分析" value={analysis.analyzed_questions} helper="questions"/><Metric label="已跳过" value={analysis.skipped_records} helper="skipped records"/></div>{analysis.warnings?.length>0&&<div className="teacher-warning">{analysis.warnings.join("、")}</div>}<div className="teacher-grid">{distributions.map(([title,items]:any)=><section key={title}><h2>{title}</h2><pre>{JSON.stringify(items,null,2)}</pre></section>)}</div><section><h2>问题主题</h2><QuestionTopics items={analysis.question_topics}/></section><section><h2>高频关键词</h2><p>{analysis.top_keywords?.map((x:any)=>`${x.keyword}(${x.count})`).join("、")}</p></section><section><h2>Skill 示例</h2><pre>{JSON.stringify(analysis.examples_by_skill,null,2)}</pre></section><section><h2>Teaching follow-ups</h2><p>{analysis.teaching_followups?.join("、")}</p></section><details><summary>Skipped examples</summary><pre>{JSON.stringify(analysis.skipped_examples,null,2)}</pre></details><details open><summary>详细分析 items</summary><pre>{JSON.stringify(analysis.items,null,2)}</pre></details></div>; }
