import { appPath } from "../../paths";
import { formatDate, skillNames, stageText } from "../teacherLabels";
import { ImportAnalysisView, MarkdownPanel, Metric, QuestionTopics, SkillDistribution } from "../components/TeacherViews";

export function OverviewPage({ model }: any) { const s=model.stats, total=(s?.skill_counts||[]).reduce((a:number,x:any)=>a+x.count,0); const priority=model.students.filter((x:any)=>x.risk_tags?.length||x.needs_teacher_confirmation).slice(0,5); return <><div className="teacher-page-heading"><h1>总览</h1></div><div className="metric-row"><Metric label="总会话数" value={s?.total_sessions} helper="累计学生会话"/><Metric label="总问题数" value={s?.total_user_messages} helper="用户消息总量"/><Metric label="今日问题" value={s?.today_user_messages} helper="当日新增"/><Metric label="Skill 调用" value={total} helper="已识别任务"/></div><div className="teacher-grid emphasis"><section><h2>班级共同卡点</h2><QuestionTopics items={(s?.question_topics||[]).slice(0,4)}/></section><section><h2>优先关注学生</h2>{priority.map((x:any)=><p key={x.session_id}><strong>{studentLabel(x)}</strong> · {x.risk_tags?.join("、")||"待教师确认"}</p>)}{!priority.length&&<p className="muted">暂无优先信号</p>}</section></div><div className="teacher-grid"><section><h2>Skill 分布摘要</h2><SkillDistribution items={(s?.skill_counts||[]).slice(0,6)}/></section><section><h2>最近活动</h2>{(s?.recent_questions||[]).slice(0,5).map((x:any)=><p key={x.session_id+x.created_at}>{formatDate(x.created_at)} · {x.content}</p>)}</section></div><section><div className="section-heading"><h2>教学摘要</h2><div><button onClick={model.summarizeTeaching} disabled={model.loadingTeaching}>{model.loadingTeaching?"生成中":"生成教学复盘"}</button><button onClick={model.summarizeClass} disabled={model.loadingClass}>{model.loadingClass?"生成中":"生成班级学情"}</button></div></div>{model.teachingSummary&&<MarkdownPanel>{model.teachingSummary}</MarkdownPanel>}{model.classSummary&&<MarkdownPanel>{model.classSummary}</MarkdownPanel>}</section></>; }

export function StudentsPage({ model }: any) { return <><div className="teacher-page-heading"><h1>学生</h1><button onClick={model.loadStudents}>刷新学生</button></div>{model.studentError&&<p className="teacher-error">{model.studentError}</p>}<div className="student-table"><div className="student-row head"><span>学生 / 学号</span><span>阶段 / Skill</span><span>追问 / 时间</span><span>风险 / 下一步</span><span>操作</span></div>{model.students.map((x:any)=><div className="student-row" key={x.session_id}><span><strong>{studentLabel(x)}</strong><small>{x.topic||x.research_question||"尚未形成主题"}</small></span><span>{stageText(x.stage)}<small>{skillNames[x.current_skill]||x.current_skill||"未识别"}</small></span><span>{x.socratic_rounds||0} 轮<small>{formatDate(x.updated_at)}</small></span><span><div className="risk-tags">{(x.risk_tags||[]).map((t:string)=><em key={t}>{t}</em>)}</div><small>{x.next_task||"继续观察"}</small></span><span className="row-actions"><button onClick={()=>model.openStudent(x.session_id,"summary")}>摘要</button><button onClick={()=>model.openStudent(x.session_id,"detail")}>详情</button><button className="danger" disabled={model.deleting===x.session_id} onClick={()=>model.deleteStudent(x.session_id)}>{model.deleting===x.session_id?"删除中":"删除"}</button></span></div>)}</div></>; }

export function ConversationsPage({ model }: any) { const hints=["我下次上课大概需要讲什么东西？","哪些学生还卡在选题？","最近学生关于文献检索问了什么？","哪些会话需要优先面批？"]; return <><div className="teacher-page-heading"><h1>对话记录</h1></div><section><h2>问学生对话库</h2><form className="archive-form" onSubmit={e=>{e.preventDefault();model.askArchive();}}><textarea value={model.archiveQuestion} onChange={(e)=>model.setArchiveQuestion(e.target.value)} rows={2}/><button disabled={model.askingArchive}>{model.askingArchive?"检索中":"提问"}</button></form><div className="quick-questions">{hints.map(x=><button key={x} onClick={()=>model.askArchive(x)}>{x}</button>)}</div>{model.archiveError&&<p className="teacher-error">{model.archiveError}</p>}<MarkdownPanel>{model.archiveAnswer||"输入教师问题后，这里会基于学生对话返回结论。"}</MarkdownPanel>{model.archiveEvidence.length>0&&<details><summary>查看命中证据（{model.archiveEvidence.length}）</summary><pre>{JSON.stringify(model.archiveEvidence,null,2)}</pre></details>}</section><section><h2>最近学生问题</h2><div className="conversation-list">{(model.stats?.recent_questions||[]).map((x:any)=><article className={x.guardrail_triggered?"guardrail":""} key={x.session_id+x.created_at}><div><time>{formatDate(x.created_at)}</time><span>{skillNames[x.skill_id]||x.skill_id||"未识别"}</span>{x.guardrail_triggered&&<em>Guardrail</em>}</div><p>{x.content}</p><small>会话 {x.session_id.slice(0,8)}</small></article>)}</div></section></>; }

export function InsightsPage({ model }: any) { const i=model.insights||{}; return <><div className="teacher-page-heading"><h1>班级洞察</h1><button onClick={model.loadInsights}>刷新洞察</button></div><div className="teacher-grid"><section><h2>Skill 使用分布</h2><SkillDistribution items={i.skill_counts||model.stats?.skill_counts}/></section><section><h2>高频问题主题</h2><QuestionTopics items={i.question_topics||model.stats?.question_topics}/></section></div><div className="teacher-grid"><section><h2>阶段分布</h2><pre>{JSON.stringify(i.stage_distribution||[],null,2)}</pre></section><section><h2>高频卡点</h2><pre>{JSON.stringify(i.top_stuck_points||[],null,2)}</pre></section><section><h2>优先面批学生</h2><pre>{JSON.stringify(i.priority_students||[],null,2)}</pre></section><section><h2>课堂建议</h2><p>{i.teaching_followups?.join("、")||"-"}</p></section></div><section><h2>高频关键词</h2><p>{(i.top_keywords||model.stats?.top_keywords||[]).map((x:any)=>`${x.keyword}(${x.count})`).join("、")}</p></section><section><div className="section-heading"><h2>教学摘要</h2><div><button onClick={model.summarizeTeaching} disabled={model.loadingTeaching}>教学复盘</button><button onClick={model.summarizeClass} disabled={model.loadingClass}>班级学情</button></div></div>{model.teachingSummary&&<MarkdownPanel>{model.teachingSummary}</MarkdownPanel>}{model.classSummary&&<MarkdownPanel>{model.classSummary}</MarkdownPanel>}</section></>; }

export function ImportPage({ model }: any) { return <><div className="teacher-page-heading"><h1>数据导入</h1></div><section className="upload-section"><label className={model.importing?"disabled":""}><input type="file" accept="application/json,.json" disabled={model.importing} onChange={e=>{model.analyzeUpload(e.target.files?.[0]||null);e.currentTarget.value="";}}/>{model.importing?"分析中":"选择 JSON 文件"}</label><p>分析结果只在当前页展示，不写入学生会话数据库。</p>{model.importError&&<p className="teacher-error">{model.importError}</p>}</section><ImportAnalysisView analysis={model.importAnalysis}/></>; }

export function SettingsPage({ model }: any) { return <><div className="teacher-page-heading"><h1>设置</h1></div><div className="settings-list"><section><h2>后端连接</h2><p><span className="backend-ok">已连接</span> 已通过教师统计接口验证。</p></section><section><h2>认证状态</h2><p>教师访问已验证；页面不显示访问码明文。</p><button className="danger" onClick={model.logout}>清除本地访问状态并退出</button></section><section><h2>数据导出</h2><p><button className="button-link" onClick={()=>model.exportData("csv")}>导出 CSV</button> <button className="button-link" onClick={()=>model.exportData("json")}>导出 JSON</button></p></section><section><h2>页面</h2><a className="button-link" href={appPath("/student")}>返回学生端</a></section><section><h2>隐私与数据</h2><p>教师端展示学生对话、写作阶段、Skill 使用和风险信号。请仅在授权教学场景中使用与导出。</p></section></div></>; }

function studentLabel(x:any){const name=x.student_name||"",id=x.student_id||x.user_id||"";return name&&id?`${name}（${id}）`:name||id||`会话 ${x.session_id.slice(0,8)}`;}
